/** Tailwind config — matches stitch UI color palette. */

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-container': '#40c2fd',
        'on-tertiary-fixed-variant': '#005236',
        'primary-fixed-dim': '#bec6e0',
        'surface-tint': '#565e74',
        'surface-container-low': '#f2f4f6',
        'on-primary-container': '#7c839b',
        'tertiary-container': '#002113',
        'on-secondary': '#ffffff',
        'surface': '#f7f9fb',
        'on-tertiary': '#ffffff',
        'secondary': '#00668a',
        'primary-container': '#131b2e',
        'tertiary-fixed-dim': '#4edea3',
        'surface-dim': '#d8dadc',
        'error': '#ba1a1a',
        'on-primary-fixed-variant': '#3f465c',
        'on-surface': '#191c1e',
        'outline': '#76777d',
        'on-tertiary-container': '#009668',
        'secondary-fixed': '#c4e7ff',
        'surface-bright': '#f7f9fb',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#6ffbbe',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#7bd0ff',
        'on-surface-variant': '#45464d',
        'outline-variant': '#c6c6cd',
        'primary': '#325da7',
        'on-background': '#191c1e',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#004c69',
        'inverse-on-surface': '#eff1f3',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'primary-fixed': '#dae2fd',
        'background': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#004d6a',
        'error-container': '#ffdad6',
        'inverse-surface': '#2d3133',
        'surface-variant': '#e0e3e5',
        'surface-container': '#eceef0',
        'on-primary-fixed': '#131b2e',
        'on-tertiary-fixed': '#002113',
        'inverse-primary': '#bec6e0',
        'on-secondary-fixed': '#001e2c',
        'tertiary': '#725573',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'container-margin': '24px',
        gutter: '16px',
        'stack-sm': '8px',
        'stack-md': '16px',
        unit: '4px',
        'stack-lg': '32px',
      },
      fontFamily: {
        'display-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'numeric-data': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'numeric-data': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
